---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
      annotations:
        kubernetes.azure.com/static-gateway-configuration: myegressgateway
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
