---
apiVersion: egressgateway.kubernetes.azure.com/v1alpha1
kind: StaticGatewayConfiguration
metadata:
  name: myegressgateway
  namespace: demo
spec:
  gatewayVmssProfile:
    vmssResourceGroup: <replace-with-your-vmmss-resource-group>
    vmssName: <replace-with-your-vmss>
  provisionPublicIps: false
  defaultRoute: azureNetworking
  excludeCidrs:
    - 10.0.0.0/16
