---
apiVersion: egressgateway.kubernetes.azure.com/v1alpha1
kind: StaticGatewayConfiguration
metadata:
  name: myegressgateway
  namespace: demo
spec:
  gatewayVmssProfile:
    vmssResourceGroup: $NODE_RESOURCE_GROUP
    vmssName: $EGRESS_VMSS_NAME
  provisionPublicIps: false
  defaultRoute: azureNetworking
  excludeCidrs:
    - 10.0.0.0/16
